// Regenerates src/fonts.css: downloads the page's web fonts from Google Fonts
// and embeds them as data URIs so the built page works offline.
//   node scripts/fetch-fonts.js
// Latin subset only (English and Western European text). Needs network access.
const fs = require('node:fs')
const path = require('node:path')

const FAMILIES =
  'family=Barlow+Semi+Condensed:wght@500;600;700' +
  '&family=IBM+Plex+Mono:wght@400;500' +
  '&family=IBM+Plex+Sans:wght@400;500;600'
const CSS_URL = `https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`
// A browser user agent makes Google Fonts serve woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
const SUBSETS = new Set(['latin'])

const HEADER = `/* Embedded web fonts so the page works offline.
 * Barlow Semi Condensed (c) Jeremy Tribby; IBM Plex Sans and IBM Plex Mono (c) IBM Corp.
 * All three are licensed under the SIL Open Font License 1.1
 * (https://openfontlicense.org): they may be embedded and redistributed with
 * the software, but not sold on their own.
 * Latin subset only. Regenerated by scripts/fetch-fonts.js.
 */
`

async function main() {
  const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()
  const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[^}]*\})/g)]
  const out = []
  let bytes = 0
  for (const [, subset, block] of blocks) {
    if (!SUBSETS.has(subset)) continue
    const url = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)[1]
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer())
    bytes += buf.length
    out.push(`/* ${subset} */\n` + block.replace(url, `data:font/woff2;base64,${buf.toString('base64')}`))
  }
  if (out.length === 0) throw new Error('No font faces found; did Google Fonts change its CSS?')
  const file = path.join(__dirname, '..', 'src', 'fonts.css')
  fs.writeFileSync(file, HEADER + out.join('\n') + '\n')
  console.log(`Wrote ${out.length} faces (${Math.round(bytes / 1024)} KB of woff2) to src/fonts.css`)
}

main().catch((e) => { console.error(e); process.exit(1) })
